import type { Evaluation } from "@/lib/domain/evaluation";
import { EvaluationStatus } from "@/lib/domain/evaluation";
import { HACKATHON_ID } from "./hackathons";

export const mockEvaluations: Evaluation[] = [
  {
    id: "eval-001",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-001",
    judgeId: "judge-ahmad",
    projectId: "project-001",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-001-score-1",
        evaluationId: "eval-001",
        criterionId: "criterion-innovation",
        score: 8.4,
        comment: "فكرة قوية وعرض واضح، يُنصح بتوسيع دراسة السوق.",
      },
      {
        id: "eval-001-score-2",
        evaluationId: "eval-001",
        criterionId: "criterion-impact",
        score: 7.8,
      },
      {
        id: "eval-001-score-3",
        evaluationId: "eval-001",
        criterionId: "criterion-feasibility",
        score: 9.4,
      },
      {
        id: "eval-001-score-4",
        evaluationId: "eval-001",
        criterionId: "criterion-presentation",
        score: 8.7,
      },
    ],
    submittedAt: "2026-08-20T10:00:00.000Z",
    createdAt: "2026-08-20T10:00:00.000Z",
    updatedAt: "2026-08-20T10:00:00.000Z",
  },
  {
    id: "eval-002",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-002",
    judgeId: "judge-mohammed",
    projectId: "project-001",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-002-score-1",
        evaluationId: "eval-002",
        criterionId: "criterion-innovation",
        score: 6.7,
      },
      {
        id: "eval-002-score-2",
        evaluationId: "eval-002",
        criterionId: "criterion-impact",
        score: 8.1,
      },
      {
        id: "eval-002-score-3",
        evaluationId: "eval-002",
        criterionId: "criterion-feasibility",
        score: 7.1,
      },
      {
        id: "eval-002-score-4",
        evaluationId: "eval-002",
        criterionId: "criterion-presentation",
        score: 8.5,
        comment: "من أفضل المشاريع من ناحية جاهزية النموذج الأولي.",
      },
    ],
    submittedAt: "2026-08-20T10:45:00.000Z",
    createdAt: "2026-08-20T10:45:00.000Z",
    updatedAt: "2026-08-20T10:45:00.000Z",
  },
  {
    id: "eval-003",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-003",
    judgeId: "judge-khalid",
    projectId: "project-001",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-003-score-1",
        evaluationId: "eval-003",
        criterionId: "criterion-innovation",
        score: 9.5,
      },
      {
        id: "eval-003-score-2",
        evaluationId: "eval-003",
        criterionId: "criterion-impact",
        score: 7.9,
      },
      {
        id: "eval-003-score-3",
        evaluationId: "eval-003",
        criterionId: "criterion-feasibility",
        score: 7,
        comment: "من أفضل المشاريع من ناحية جاهزية النموذج الأولي.",
      },
      {
        id: "eval-003-score-4",
        evaluationId: "eval-003",
        criterionId: "criterion-presentation",
        score: 9.5,
      },
    ],
    submittedAt: "2026-08-20T11:30:00.000Z",
    createdAt: "2026-08-20T11:30:00.000Z",
    updatedAt: "2026-08-20T11:30:00.000Z",
  },
  {
    id: "eval-004",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-004",
    judgeId: "judge-sarah",
    projectId: "project-001",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-004-score-1",
        evaluationId: "eval-004",
        criterionId: "criterion-innovation",
        score: 9,
      },
      {
        id: "eval-004-score-2",
        evaluationId: "eval-004",
        criterionId: "criterion-impact",
        score: 7.2,
        comment: "من أفضل المشاريع من ناحية جاهزية النموذج الأولي.",
      },
      {
        id: "eval-004-score-3",
        evaluationId: "eval-004",
        criterionId: "criterion-feasibility",
        score: 6.8,
      },
      {
        id: "eval-004-score-4",
        evaluationId: "eval-004",
        criterionId: "criterion-presentation",
        score: 8,
      },
    ],
    submittedAt: "2026-08-20T12:15:00.000Z",
    createdAt: "2026-08-20T12:15:00.000Z",
    updatedAt: "2026-08-20T12:15:00.000Z",
  },
  {
    id: "eval-005",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-005",
    judgeId: "judge-nora",
    projectId: "project-001",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-005-score-1",
        evaluationId: "eval-005",
        criterionId: "criterion-innovation",
        score: 8.7,
        comment: "من أفضل المشاريع من ناحية جاهزية النموذج الأولي.",
      },
      {
        id: "eval-005-score-2",
        evaluationId: "eval-005",
        criterionId: "criterion-impact",
        score: 8.4,
      },
      {
        id: "eval-005-score-3",
        evaluationId: "eval-005",
        criterionId: "criterion-feasibility",
        score: 6,
      },
      {
        id: "eval-005-score-4",
        evaluationId: "eval-005",
        criterionId: "criterion-presentation",
        score: 7.9,
      },
    ],
    submittedAt: "2026-08-20T13:00:00.000Z",
    createdAt: "2026-08-20T13:00:00.000Z",
    updatedAt: "2026-08-20T13:00:00.000Z",
  },
  {
    id: "eval-006",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-006",
    judgeId: "judge-ahmad",
    projectId: "project-002",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-006-score-1",
        evaluationId: "eval-006",
        criterionId: "criterion-innovation",
        score: 9.3,
      },
      {
        id: "eval-006-score-2",
        evaluationId: "eval-006",
        criterionId: "criterion-impact",
        score: 6.2,
      },
      {
        id: "eval-006-score-3",
        evaluationId: "eval-006",
        criterionId: "criterion-feasibility",
        score: 8.4,
      },
      {
        id: "eval-006-score-4",
        evaluationId: "eval-006",
        criterionId: "criterion-presentation",
        score: 6.1,
        comment: "يحتاج الفريق لتوضيح خطة التوسّع بعد الإطلاق.",
      },
    ],
    submittedAt: "2026-08-20T13:45:00.000Z",
    createdAt: "2026-08-20T13:45:00.000Z",
    updatedAt: "2026-08-20T13:45:00.000Z",
  },
  {
    id: "eval-007",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-007",
    judgeId: "judge-mohammed",
    projectId: "project-002",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-007-score-1",
        evaluationId: "eval-007",
        criterionId: "criterion-innovation",
        score: 7.1,
      },
      {
        id: "eval-007-score-2",
        evaluationId: "eval-007",
        criterionId: "criterion-impact",
        score: 6.2,
      },
      {
        id: "eval-007-score-3",
        evaluationId: "eval-007",
        criterionId: "criterion-feasibility",
        score: 6.7,
        comment: "يحتاج الفريق لتوضيح خطة التوسّع بعد الإطلاق.",
      },
      {
        id: "eval-007-score-4",
        evaluationId: "eval-007",
        criterionId: "criterion-presentation",
        score: 9.1,
      },
    ],
    submittedAt: "2026-08-20T14:30:00.000Z",
    createdAt: "2026-08-20T14:30:00.000Z",
    updatedAt: "2026-08-20T14:30:00.000Z",
  },
  {
    id: "eval-008",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-008",
    judgeId: "judge-khalid",
    projectId: "project-002",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-008-score-1",
        evaluationId: "eval-008",
        criterionId: "criterion-innovation",
        score: 8.1,
      },
      {
        id: "eval-008-score-2",
        evaluationId: "eval-008",
        criterionId: "criterion-impact",
        score: 6.1,
        comment: "يحتاج الفريق لتوضيح خطة التوسّع بعد الإطلاق.",
      },
      {
        id: "eval-008-score-3",
        evaluationId: "eval-008",
        criterionId: "criterion-feasibility",
        score: 6.7,
      },
      {
        id: "eval-008-score-4",
        evaluationId: "eval-008",
        criterionId: "criterion-presentation",
        score: 9.4,
      },
    ],
    submittedAt: "2026-08-20T15:15:00.000Z",
    createdAt: "2026-08-20T15:15:00.000Z",
    updatedAt: "2026-08-20T15:15:00.000Z",
  },
  {
    id: "eval-009",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-009",
    judgeId: "judge-sarah",
    projectId: "project-002",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-009-score-1",
        evaluationId: "eval-009",
        criterionId: "criterion-innovation",
        score: 8,
        comment: "يحتاج الفريق لتوضيح خطة التوسّع بعد الإطلاق.",
      },
      {
        id: "eval-009-score-2",
        evaluationId: "eval-009",
        criterionId: "criterion-impact",
        score: 9.2,
      },
      {
        id: "eval-009-score-3",
        evaluationId: "eval-009",
        criterionId: "criterion-feasibility",
        score: 7.3,
      },
      {
        id: "eval-009-score-4",
        evaluationId: "eval-009",
        criterionId: "criterion-presentation",
        score: 7.8,
      },
    ],
    submittedAt: "2026-08-20T16:00:00.000Z",
    createdAt: "2026-08-20T16:00:00.000Z",
    updatedAt: "2026-08-20T16:00:00.000Z",
  },
  {
    id: "eval-010",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-010",
    judgeId: "judge-nora",
    projectId: "project-002",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-010-score-1",
        evaluationId: "eval-010",
        criterionId: "criterion-innovation",
        score: 6.1,
      },
      {
        id: "eval-010-score-2",
        evaluationId: "eval-010",
        criterionId: "criterion-impact",
        score: 6.2,
      },
      {
        id: "eval-010-score-3",
        evaluationId: "eval-010",
        criterionId: "criterion-feasibility",
        score: 8.2,
      },
      {
        id: "eval-010-score-4",
        evaluationId: "eval-010",
        criterionId: "criterion-presentation",
        score: 8.4,
        comment: "عرض تقديمي مقنع ومؤشرات أداء واقعية.",
      },
    ],
    submittedAt: "2026-08-20T16:45:00.000Z",
    createdAt: "2026-08-20T16:45:00.000Z",
    updatedAt: "2026-08-20T16:45:00.000Z",
  },
  {
    id: "eval-011",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-011",
    judgeId: "judge-ahmad",
    projectId: "project-003",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-011-score-1",
        evaluationId: "eval-011",
        criterionId: "criterion-innovation",
        score: 7,
      },
      {
        id: "eval-011-score-2",
        evaluationId: "eval-011",
        criterionId: "criterion-impact",
        score: 8.6,
      },
      {
        id: "eval-011-score-3",
        evaluationId: "eval-011",
        criterionId: "criterion-feasibility",
        score: 6.8,
        comment: "عرض تقديمي مقنع ومؤشرات أداء واقعية.",
      },
      {
        id: "eval-011-score-4",
        evaluationId: "eval-011",
        criterionId: "criterion-presentation",
        score: 7.2,
      },
    ],
    submittedAt: "2026-08-20T17:30:00.000Z",
    createdAt: "2026-08-20T17:30:00.000Z",
    updatedAt: "2026-08-20T17:30:00.000Z",
  },
  {
    id: "eval-012",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-012",
    judgeId: "judge-mohammed",
    projectId: "project-003",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-012-score-1",
        evaluationId: "eval-012",
        criterionId: "criterion-innovation",
        score: 9,
      },
      {
        id: "eval-012-score-2",
        evaluationId: "eval-012",
        criterionId: "criterion-impact",
        score: 9.4,
        comment: "عرض تقديمي مقنع ومؤشرات أداء واقعية.",
      },
      {
        id: "eval-012-score-3",
        evaluationId: "eval-012",
        criterionId: "criterion-feasibility",
        score: 8,
      },
      {
        id: "eval-012-score-4",
        evaluationId: "eval-012",
        criterionId: "criterion-presentation",
        score: 6.8,
      },
    ],
    submittedAt: "2026-08-20T18:15:00.000Z",
    createdAt: "2026-08-20T18:15:00.000Z",
    updatedAt: "2026-08-20T18:15:00.000Z",
  },
  {
    id: "eval-013",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-013",
    judgeId: "judge-khalid",
    projectId: "project-003",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-013-score-1",
        evaluationId: "eval-013",
        criterionId: "criterion-innovation",
        score: 7.1,
        comment: "عرض تقديمي مقنع ومؤشرات أداء واقعية.",
      },
      {
        id: "eval-013-score-2",
        evaluationId: "eval-013",
        criterionId: "criterion-impact",
        score: 7.2,
      },
      {
        id: "eval-013-score-3",
        evaluationId: "eval-013",
        criterionId: "criterion-feasibility",
        score: 6.3,
      },
      {
        id: "eval-013-score-4",
        evaluationId: "eval-013",
        criterionId: "criterion-presentation",
        score: 8.6,
      },
    ],
    submittedAt: "2026-08-20T19:00:00.000Z",
    createdAt: "2026-08-20T19:00:00.000Z",
    updatedAt: "2026-08-20T19:00:00.000Z",
  },
  {
    id: "eval-014",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-014",
    judgeId: "judge-sarah",
    projectId: "project-003",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-014-score-1",
        evaluationId: "eval-014",
        criterionId: "criterion-innovation",
        score: 8.7,
      },
      {
        id: "eval-014-score-2",
        evaluationId: "eval-014",
        criterionId: "criterion-impact",
        score: 8.8,
      },
      {
        id: "eval-014-score-3",
        evaluationId: "eval-014",
        criterionId: "criterion-feasibility",
        score: 9.7,
      },
      {
        id: "eval-014-score-4",
        evaluationId: "eval-014",
        criterionId: "criterion-presentation",
        score: 6.4,
        comment: "تنفيذ تقني متقن لكن الأثر المجتمعي يحتاج توضيحًا أكبر.",
      },
    ],
    submittedAt: "2026-08-20T19:45:00.000Z",
    createdAt: "2026-08-20T19:45:00.000Z",
    updatedAt: "2026-08-20T19:45:00.000Z",
  },
  {
    id: "eval-015",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-015",
    judgeId: "judge-nora",
    projectId: "project-003",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-015-score-1",
        evaluationId: "eval-015",
        criterionId: "criterion-innovation",
        score: 9.8,
      },
      {
        id: "eval-015-score-2",
        evaluationId: "eval-015",
        criterionId: "criterion-impact",
        score: 7.7,
      },
      {
        id: "eval-015-score-3",
        evaluationId: "eval-015",
        criterionId: "criterion-feasibility",
        score: 9.8,
        comment: "تنفيذ تقني متقن لكن الأثر المجتمعي يحتاج توضيحًا أكبر.",
      },
      {
        id: "eval-015-score-4",
        evaluationId: "eval-015",
        criterionId: "criterion-presentation",
        score: 6.5,
      },
    ],
    submittedAt: "2026-08-20T20:30:00.000Z",
    createdAt: "2026-08-20T20:30:00.000Z",
    updatedAt: "2026-08-20T20:30:00.000Z",
  },
  {
    id: "eval-016",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-016",
    judgeId: "judge-ahmad",
    projectId: "project-004",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-016-score-1",
        evaluationId: "eval-016",
        criterionId: "criterion-innovation",
        score: 6.4,
      },
      {
        id: "eval-016-score-2",
        evaluationId: "eval-016",
        criterionId: "criterion-impact",
        score: 6.1,
        comment: "تنفيذ تقني متقن لكن الأثر المجتمعي يحتاج توضيحًا أكبر.",
      },
      {
        id: "eval-016-score-3",
        evaluationId: "eval-016",
        criterionId: "criterion-feasibility",
        score: 7.4,
      },
      {
        id: "eval-016-score-4",
        evaluationId: "eval-016",
        criterionId: "criterion-presentation",
        score: 7.9,
      },
    ],
    submittedAt: "2026-08-20T21:15:00.000Z",
    createdAt: "2026-08-20T21:15:00.000Z",
    updatedAt: "2026-08-20T21:15:00.000Z",
  },
  {
    id: "eval-017",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-017",
    judgeId: "judge-mohammed",
    projectId: "project-004",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-017-score-1",
        evaluationId: "eval-017",
        criterionId: "criterion-innovation",
        score: 8.4,
        comment: "تنفيذ تقني متقن لكن الأثر المجتمعي يحتاج توضيحًا أكبر.",
      },
      {
        id: "eval-017-score-2",
        evaluationId: "eval-017",
        criterionId: "criterion-impact",
        score: 9.6,
      },
      {
        id: "eval-017-score-3",
        evaluationId: "eval-017",
        criterionId: "criterion-feasibility",
        score: 6.3,
      },
      {
        id: "eval-017-score-4",
        evaluationId: "eval-017",
        criterionId: "criterion-presentation",
        score: 8.9,
      },
    ],
    submittedAt: "2026-08-20T22:00:00.000Z",
    createdAt: "2026-08-20T22:00:00.000Z",
    updatedAt: "2026-08-20T22:00:00.000Z",
  },
  {
    id: "eval-018",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-018",
    judgeId: "judge-khalid",
    projectId: "project-004",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-018-score-1",
        evaluationId: "eval-018",
        criterionId: "criterion-innovation",
        score: 9.7,
      },
      {
        id: "eval-018-score-2",
        evaluationId: "eval-018",
        criterionId: "criterion-impact",
        score: 7.1,
      },
      {
        id: "eval-018-score-3",
        evaluationId: "eval-018",
        criterionId: "criterion-feasibility",
        score: 8.8,
      },
      {
        id: "eval-018-score-4",
        evaluationId: "eval-018",
        criterionId: "criterion-presentation",
        score: 6.7,
        comment: "فكرة قوية وعرض واضح، يُنصح بتوسيع دراسة السوق.",
      },
    ],
    submittedAt: "2026-08-20T22:45:00.000Z",
    createdAt: "2026-08-20T22:45:00.000Z",
    updatedAt: "2026-08-20T22:45:00.000Z",
  },
  {
    id: "eval-019",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-019",
    judgeId: "judge-sarah",
    projectId: "project-004",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-019-score-1",
        evaluationId: "eval-019",
        criterionId: "criterion-innovation",
        score: 8.1,
      },
      {
        id: "eval-019-score-2",
        evaluationId: "eval-019",
        criterionId: "criterion-impact",
        score: 9.3,
      },
      {
        id: "eval-019-score-3",
        evaluationId: "eval-019",
        criterionId: "criterion-feasibility",
        score: 6.5,
        comment: "فكرة قوية وعرض واضح، يُنصح بتوسيع دراسة السوق.",
      },
      {
        id: "eval-019-score-4",
        evaluationId: "eval-019",
        criterionId: "criterion-presentation",
        score: 10,
      },
    ],
    submittedAt: "2026-08-20T23:30:00.000Z",
    createdAt: "2026-08-20T23:30:00.000Z",
    updatedAt: "2026-08-20T23:30:00.000Z",
  },
  {
    id: "eval-020",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-020",
    judgeId: "judge-nora",
    projectId: "project-004",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-020-score-1",
        evaluationId: "eval-020",
        criterionId: "criterion-innovation",
        score: 8.3,
      },
      {
        id: "eval-020-score-2",
        evaluationId: "eval-020",
        criterionId: "criterion-impact",
        score: 9.7,
        comment: "فكرة قوية وعرض واضح، يُنصح بتوسيع دراسة السوق.",
      },
      {
        id: "eval-020-score-3",
        evaluationId: "eval-020",
        criterionId: "criterion-feasibility",
        score: 7.7,
      },
      {
        id: "eval-020-score-4",
        evaluationId: "eval-020",
        criterionId: "criterion-presentation",
        score: 8.3,
      },
    ],
    submittedAt: "2026-08-21T00:15:00.000Z",
    createdAt: "2026-08-21T00:15:00.000Z",
    updatedAt: "2026-08-21T00:15:00.000Z",
  },
  {
    id: "eval-021",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-021",
    judgeId: "judge-ahmad",
    projectId: "project-005",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-021-score-1",
        evaluationId: "eval-021",
        criterionId: "criterion-innovation",
        score: 7.3,
        comment: "فكرة قوية وعرض واضح، يُنصح بتوسيع دراسة السوق.",
      },
      {
        id: "eval-021-score-2",
        evaluationId: "eval-021",
        criterionId: "criterion-impact",
        score: 8.4,
      },
      {
        id: "eval-021-score-3",
        evaluationId: "eval-021",
        criterionId: "criterion-feasibility",
        score: 7.3,
      },
      {
        id: "eval-021-score-4",
        evaluationId: "eval-021",
        criterionId: "criterion-presentation",
        score: 8.9,
      },
    ],
    submittedAt: "2026-08-21T01:00:00.000Z",
    createdAt: "2026-08-21T01:00:00.000Z",
    updatedAt: "2026-08-21T01:00:00.000Z",
  },
  {
    id: "eval-022",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-022",
    judgeId: "judge-mohammed",
    projectId: "project-005",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-022-score-1",
        evaluationId: "eval-022",
        criterionId: "criterion-innovation",
        score: 7.2,
      },
      {
        id: "eval-022-score-2",
        evaluationId: "eval-022",
        criterionId: "criterion-impact",
        score: 7.8,
      },
      {
        id: "eval-022-score-3",
        evaluationId: "eval-022",
        criterionId: "criterion-feasibility",
        score: 9.4,
      },
      {
        id: "eval-022-score-4",
        evaluationId: "eval-022",
        criterionId: "criterion-presentation",
        score: 8.8,
        comment: "من أفضل المشاريع من ناحية جاهزية النموذج الأولي.",
      },
    ],
    submittedAt: "2026-08-21T01:45:00.000Z",
    createdAt: "2026-08-21T01:45:00.000Z",
    updatedAt: "2026-08-21T01:45:00.000Z",
  },
  {
    id: "eval-023",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-023",
    judgeId: "judge-khalid",
    projectId: "project-005",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-023-score-1",
        evaluationId: "eval-023",
        criterionId: "criterion-innovation",
        score: 10,
      },
      {
        id: "eval-023-score-2",
        evaluationId: "eval-023",
        criterionId: "criterion-impact",
        score: 9.6,
      },
      {
        id: "eval-023-score-3",
        evaluationId: "eval-023",
        criterionId: "criterion-feasibility",
        score: 7.7,
        comment: "من أفضل المشاريع من ناحية جاهزية النموذج الأولي.",
      },
      {
        id: "eval-023-score-4",
        evaluationId: "eval-023",
        criterionId: "criterion-presentation",
        score: 8.2,
      },
    ],
    submittedAt: "2026-08-21T02:30:00.000Z",
    createdAt: "2026-08-21T02:30:00.000Z",
    updatedAt: "2026-08-21T02:30:00.000Z",
  },
  {
    id: "eval-024",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-024",
    judgeId: "judge-sarah",
    projectId: "project-005",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-024-score-1",
        evaluationId: "eval-024",
        criterionId: "criterion-innovation",
        score: 7.2,
      },
      {
        id: "eval-024-score-2",
        evaluationId: "eval-024",
        criterionId: "criterion-impact",
        score: 6.4,
        comment: "من أفضل المشاريع من ناحية جاهزية النموذج الأولي.",
      },
      {
        id: "eval-024-score-3",
        evaluationId: "eval-024",
        criterionId: "criterion-feasibility",
        score: 8.8,
      },
      {
        id: "eval-024-score-4",
        evaluationId: "eval-024",
        criterionId: "criterion-presentation",
        score: 7.3,
      },
    ],
    submittedAt: "2026-08-21T03:15:00.000Z",
    createdAt: "2026-08-21T03:15:00.000Z",
    updatedAt: "2026-08-21T03:15:00.000Z",
  },
  {
    id: "eval-025",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-025",
    judgeId: "judge-nora",
    projectId: "project-005",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-025-score-1",
        evaluationId: "eval-025",
        criterionId: "criterion-innovation",
        score: 9.1,
        comment: "من أفضل المشاريع من ناحية جاهزية النموذج الأولي.",
      },
      {
        id: "eval-025-score-2",
        evaluationId: "eval-025",
        criterionId: "criterion-impact",
        score: 9.6,
      },
      {
        id: "eval-025-score-3",
        evaluationId: "eval-025",
        criterionId: "criterion-feasibility",
        score: 6.4,
      },
      {
        id: "eval-025-score-4",
        evaluationId: "eval-025",
        criterionId: "criterion-presentation",
        score: 7.9,
      },
    ],
    submittedAt: "2026-08-21T04:00:00.000Z",
    createdAt: "2026-08-21T04:00:00.000Z",
    updatedAt: "2026-08-21T04:00:00.000Z",
  },
  {
    id: "eval-026",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-026",
    judgeId: "judge-ahmad",
    projectId: "project-006",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-026-score-1",
        evaluationId: "eval-026",
        criterionId: "criterion-innovation",
        score: 9.3,
      },
      {
        id: "eval-026-score-2",
        evaluationId: "eval-026",
        criterionId: "criterion-impact",
        score: 6.5,
      },
      {
        id: "eval-026-score-3",
        evaluationId: "eval-026",
        criterionId: "criterion-feasibility",
        score: 9.9,
      },
      {
        id: "eval-026-score-4",
        evaluationId: "eval-026",
        criterionId: "criterion-presentation",
        score: 6.7,
        comment: "يحتاج الفريق لتوضيح خطة التوسّع بعد الإطلاق.",
      },
    ],
    submittedAt: "2026-08-21T04:45:00.000Z",
    createdAt: "2026-08-21T04:45:00.000Z",
    updatedAt: "2026-08-21T04:45:00.000Z",
  },
  {
    id: "eval-027",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-027",
    judgeId: "judge-mohammed",
    projectId: "project-006",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-027-score-1",
        evaluationId: "eval-027",
        criterionId: "criterion-innovation",
        score: 8.8,
      },
      {
        id: "eval-027-score-2",
        evaluationId: "eval-027",
        criterionId: "criterion-impact",
        score: 8.8,
      },
      {
        id: "eval-027-score-3",
        evaluationId: "eval-027",
        criterionId: "criterion-feasibility",
        score: 6.9,
        comment: "يحتاج الفريق لتوضيح خطة التوسّع بعد الإطلاق.",
      },
      {
        id: "eval-027-score-4",
        evaluationId: "eval-027",
        criterionId: "criterion-presentation",
        score: 7.7,
      },
    ],
    submittedAt: "2026-08-21T05:30:00.000Z",
    createdAt: "2026-08-21T05:30:00.000Z",
    updatedAt: "2026-08-21T05:30:00.000Z",
  },
  {
    id: "eval-028",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-028",
    judgeId: "judge-khalid",
    projectId: "project-006",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-028-score-1",
        evaluationId: "eval-028",
        criterionId: "criterion-innovation",
        score: 6.7,
      },
      {
        id: "eval-028-score-2",
        evaluationId: "eval-028",
        criterionId: "criterion-impact",
        score: 8.6,
        comment: "يحتاج الفريق لتوضيح خطة التوسّع بعد الإطلاق.",
      },
      {
        id: "eval-028-score-3",
        evaluationId: "eval-028",
        criterionId: "criterion-feasibility",
        score: 7.3,
      },
      {
        id: "eval-028-score-4",
        evaluationId: "eval-028",
        criterionId: "criterion-presentation",
        score: 6.8,
      },
    ],
    submittedAt: "2026-08-21T06:15:00.000Z",
    createdAt: "2026-08-21T06:15:00.000Z",
    updatedAt: "2026-08-21T06:15:00.000Z",
  },
  {
    id: "eval-029",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-029",
    judgeId: "judge-sarah",
    projectId: "project-006",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-029-score-1",
        evaluationId: "eval-029",
        criterionId: "criterion-innovation",
        score: 8.5,
        comment: "يحتاج الفريق لتوضيح خطة التوسّع بعد الإطلاق.",
      },
      {
        id: "eval-029-score-2",
        evaluationId: "eval-029",
        criterionId: "criterion-impact",
        score: 9.5,
      },
      {
        id: "eval-029-score-3",
        evaluationId: "eval-029",
        criterionId: "criterion-feasibility",
        score: 7.3,
      },
      {
        id: "eval-029-score-4",
        evaluationId: "eval-029",
        criterionId: "criterion-presentation",
        score: 9.2,
      },
    ],
    submittedAt: "2026-08-21T07:00:00.000Z",
    createdAt: "2026-08-21T07:00:00.000Z",
    updatedAt: "2026-08-21T07:00:00.000Z",
  },
  {
    id: "eval-030",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-030",
    judgeId: "judge-nora",
    projectId: "project-006",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-030-score-1",
        evaluationId: "eval-030",
        criterionId: "criterion-innovation",
        score: 7.6,
      },
      {
        id: "eval-030-score-2",
        evaluationId: "eval-030",
        criterionId: "criterion-impact",
        score: 6.5,
      },
      {
        id: "eval-030-score-3",
        evaluationId: "eval-030",
        criterionId: "criterion-feasibility",
        score: 9.5,
      },
      {
        id: "eval-030-score-4",
        evaluationId: "eval-030",
        criterionId: "criterion-presentation",
        score: 7.5,
        comment: "عرض تقديمي مقنع ومؤشرات أداء واقعية.",
      },
    ],
    submittedAt: "2026-08-21T07:45:00.000Z",
    createdAt: "2026-08-21T07:45:00.000Z",
    updatedAt: "2026-08-21T07:45:00.000Z",
  },
  {
    id: "eval-031",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-031",
    judgeId: "judge-ahmad",
    projectId: "project-007",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-031-score-1",
        evaluationId: "eval-031",
        criterionId: "criterion-innovation",
        score: 6,
      },
      {
        id: "eval-031-score-2",
        evaluationId: "eval-031",
        criterionId: "criterion-impact",
        score: 8.9,
      },
      {
        id: "eval-031-score-3",
        evaluationId: "eval-031",
        criterionId: "criterion-feasibility",
        score: 8.5,
        comment: "عرض تقديمي مقنع ومؤشرات أداء واقعية.",
      },
      {
        id: "eval-031-score-4",
        evaluationId: "eval-031",
        criterionId: "criterion-presentation",
        score: 9.5,
      },
    ],
    submittedAt: "2026-08-21T08:30:00.000Z",
    createdAt: "2026-08-21T08:30:00.000Z",
    updatedAt: "2026-08-21T08:30:00.000Z",
  },
  {
    id: "eval-032",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-032",
    judgeId: "judge-mohammed",
    projectId: "project-007",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-032-score-1",
        evaluationId: "eval-032",
        criterionId: "criterion-innovation",
        score: 9.6,
      },
      {
        id: "eval-032-score-2",
        evaluationId: "eval-032",
        criterionId: "criterion-impact",
        score: 6.8,
        comment: "عرض تقديمي مقنع ومؤشرات أداء واقعية.",
      },
      {
        id: "eval-032-score-3",
        evaluationId: "eval-032",
        criterionId: "criterion-feasibility",
        score: 8.4,
      },
      {
        id: "eval-032-score-4",
        evaluationId: "eval-032",
        criterionId: "criterion-presentation",
        score: 8,
      },
    ],
    submittedAt: "2026-08-21T09:15:00.000Z",
    createdAt: "2026-08-21T09:15:00.000Z",
    updatedAt: "2026-08-21T09:15:00.000Z",
  },
  {
    id: "eval-033",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-033",
    judgeId: "judge-khalid",
    projectId: "project-007",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-033-score-1",
        evaluationId: "eval-033",
        criterionId: "criterion-innovation",
        score: 6.7,
        comment: "عرض تقديمي مقنع ومؤشرات أداء واقعية.",
      },
      {
        id: "eval-033-score-2",
        evaluationId: "eval-033",
        criterionId: "criterion-impact",
        score: 6.2,
      },
      {
        id: "eval-033-score-3",
        evaluationId: "eval-033",
        criterionId: "criterion-feasibility",
        score: 8.8,
      },
      {
        id: "eval-033-score-4",
        evaluationId: "eval-033",
        criterionId: "criterion-presentation",
        score: 8.8,
      },
    ],
    submittedAt: "2026-08-21T10:00:00.000Z",
    createdAt: "2026-08-21T10:00:00.000Z",
    updatedAt: "2026-08-21T10:00:00.000Z",
  },
  {
    id: "eval-034",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-034",
    judgeId: "judge-sarah",
    projectId: "project-007",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-034-score-1",
        evaluationId: "eval-034",
        criterionId: "criterion-innovation",
        score: 7.2,
      },
      {
        id: "eval-034-score-2",
        evaluationId: "eval-034",
        criterionId: "criterion-impact",
        score: 7.1,
      },
      {
        id: "eval-034-score-3",
        evaluationId: "eval-034",
        criterionId: "criterion-feasibility",
        score: 7.3,
      },
      {
        id: "eval-034-score-4",
        evaluationId: "eval-034",
        criterionId: "criterion-presentation",
        score: 6.1,
        comment: "تنفيذ تقني متقن لكن الأثر المجتمعي يحتاج توضيحًا أكبر.",
      },
    ],
    submittedAt: "2026-08-21T10:45:00.000Z",
    createdAt: "2026-08-21T10:45:00.000Z",
    updatedAt: "2026-08-21T10:45:00.000Z",
  },
  {
    id: "eval-035",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-035",
    judgeId: "judge-nora",
    projectId: "project-007",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-035-score-1",
        evaluationId: "eval-035",
        criterionId: "criterion-innovation",
        score: 6.9,
      },
      {
        id: "eval-035-score-2",
        evaluationId: "eval-035",
        criterionId: "criterion-impact",
        score: 10,
      },
      {
        id: "eval-035-score-3",
        evaluationId: "eval-035",
        criterionId: "criterion-feasibility",
        score: 8.3,
        comment: "تنفيذ تقني متقن لكن الأثر المجتمعي يحتاج توضيحًا أكبر.",
      },
      {
        id: "eval-035-score-4",
        evaluationId: "eval-035",
        criterionId: "criterion-presentation",
        score: 10,
      },
    ],
    submittedAt: "2026-08-21T11:30:00.000Z",
    createdAt: "2026-08-21T11:30:00.000Z",
    updatedAt: "2026-08-21T11:30:00.000Z",
  },
  {
    id: "eval-036",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-036",
    judgeId: "judge-ahmad",
    projectId: "project-008",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-036-score-1",
        evaluationId: "eval-036",
        criterionId: "criterion-innovation",
        score: 6.7,
      },
      {
        id: "eval-036-score-2",
        evaluationId: "eval-036",
        criterionId: "criterion-impact",
        score: 6.7,
        comment: "تنفيذ تقني متقن لكن الأثر المجتمعي يحتاج توضيحًا أكبر.",
      },
      {
        id: "eval-036-score-3",
        evaluationId: "eval-036",
        criterionId: "criterion-feasibility",
        score: 8.2,
      },
      {
        id: "eval-036-score-4",
        evaluationId: "eval-036",
        criterionId: "criterion-presentation",
        score: 7.2,
      },
    ],
    submittedAt: "2026-08-21T12:15:00.000Z",
    createdAt: "2026-08-21T12:15:00.000Z",
    updatedAt: "2026-08-21T12:15:00.000Z",
  },
  {
    id: "eval-037",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-037",
    judgeId: "judge-mohammed",
    projectId: "project-008",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-037-score-1",
        evaluationId: "eval-037",
        criterionId: "criterion-innovation",
        score: 7.6,
        comment: "تنفيذ تقني متقن لكن الأثر المجتمعي يحتاج توضيحًا أكبر.",
      },
      {
        id: "eval-037-score-2",
        evaluationId: "eval-037",
        criterionId: "criterion-impact",
        score: 7.7,
      },
      {
        id: "eval-037-score-3",
        evaluationId: "eval-037",
        criterionId: "criterion-feasibility",
        score: 7.7,
      },
      {
        id: "eval-037-score-4",
        evaluationId: "eval-037",
        criterionId: "criterion-presentation",
        score: 8.7,
      },
    ],
    submittedAt: "2026-08-21T13:00:00.000Z",
    createdAt: "2026-08-21T13:00:00.000Z",
    updatedAt: "2026-08-21T13:00:00.000Z",
  },
  {
    id: "eval-038",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-038",
    judgeId: "judge-khalid",
    projectId: "project-008",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-038-score-1",
        evaluationId: "eval-038",
        criterionId: "criterion-innovation",
        score: 7.6,
      },
      {
        id: "eval-038-score-2",
        evaluationId: "eval-038",
        criterionId: "criterion-impact",
        score: 7.3,
      },
      {
        id: "eval-038-score-3",
        evaluationId: "eval-038",
        criterionId: "criterion-feasibility",
        score: 9.6,
      },
      {
        id: "eval-038-score-4",
        evaluationId: "eval-038",
        criterionId: "criterion-presentation",
        score: 7.3,
        comment: "فكرة قوية وعرض واضح، يُنصح بتوسيع دراسة السوق.",
      },
    ],
    submittedAt: "2026-08-21T13:45:00.000Z",
    createdAt: "2026-08-21T13:45:00.000Z",
    updatedAt: "2026-08-21T13:45:00.000Z",
  },
  {
    id: "eval-039",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-039",
    judgeId: "judge-sarah",
    projectId: "project-008",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-039-score-1",
        evaluationId: "eval-039",
        criterionId: "criterion-innovation",
        score: 8,
      },
      {
        id: "eval-039-score-2",
        evaluationId: "eval-039",
        criterionId: "criterion-impact",
        score: 8.4,
      },
      {
        id: "eval-039-score-3",
        evaluationId: "eval-039",
        criterionId: "criterion-feasibility",
        score: 8.2,
        comment: "فكرة قوية وعرض واضح، يُنصح بتوسيع دراسة السوق.",
      },
      {
        id: "eval-039-score-4",
        evaluationId: "eval-039",
        criterionId: "criterion-presentation",
        score: 8.4,
      },
    ],
    submittedAt: "2026-08-21T14:30:00.000Z",
    createdAt: "2026-08-21T14:30:00.000Z",
    updatedAt: "2026-08-21T14:30:00.000Z",
  },
  {
    id: "eval-040",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-041",
    judgeId: "judge-ahmad",
    projectId: "project-009",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-040-score-1",
        evaluationId: "eval-040",
        criterionId: "criterion-innovation",
        score: 6.9,
      },
      {
        id: "eval-040-score-2",
        evaluationId: "eval-040",
        criterionId: "criterion-impact",
        score: 7.3,
        comment: "فكرة قوية وعرض واضح، يُنصح بتوسيع دراسة السوق.",
      },
      {
        id: "eval-040-score-3",
        evaluationId: "eval-040",
        criterionId: "criterion-feasibility",
        score: 7.2,
      },
      {
        id: "eval-040-score-4",
        evaluationId: "eval-040",
        criterionId: "criterion-presentation",
        score: 7.3,
      },
    ],
    submittedAt: "2026-08-21T15:15:00.000Z",
    createdAt: "2026-08-21T15:15:00.000Z",
    updatedAt: "2026-08-21T15:15:00.000Z",
  },
  {
    id: "eval-041",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-043",
    judgeId: "judge-khalid",
    projectId: "project-009",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-041-score-1",
        evaluationId: "eval-041",
        criterionId: "criterion-innovation",
        score: 8.7,
        comment: "فكرة قوية وعرض واضح، يُنصح بتوسيع دراسة السوق.",
      },
      {
        id: "eval-041-score-2",
        evaluationId: "eval-041",
        criterionId: "criterion-impact",
        score: 6.9,
      },
      {
        id: "eval-041-score-3",
        evaluationId: "eval-041",
        criterionId: "criterion-feasibility",
        score: 6.7,
      },
      {
        id: "eval-041-score-4",
        evaluationId: "eval-041",
        criterionId: "criterion-presentation",
        score: 8.8,
      },
    ],
    submittedAt: "2026-08-21T16:00:00.000Z",
    createdAt: "2026-08-21T16:00:00.000Z",
    updatedAt: "2026-08-21T16:00:00.000Z",
  },
  {
    id: "eval-042",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-044",
    judgeId: "judge-sarah",
    projectId: "project-009",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-042-score-1",
        evaluationId: "eval-042",
        criterionId: "criterion-innovation",
        score: 7.3,
      },
      {
        id: "eval-042-score-2",
        evaluationId: "eval-042",
        criterionId: "criterion-impact",
        score: 6.5,
      },
      {
        id: "eval-042-score-3",
        evaluationId: "eval-042",
        criterionId: "criterion-feasibility",
        score: 7.3,
      },
      {
        id: "eval-042-score-4",
        evaluationId: "eval-042",
        criterionId: "criterion-presentation",
        score: 6.2,
        comment: "من أفضل المشاريع من ناحية جاهزية النموذج الأولي.",
      },
    ],
    submittedAt: "2026-08-21T16:45:00.000Z",
    createdAt: "2026-08-21T16:45:00.000Z",
    updatedAt: "2026-08-21T16:45:00.000Z",
  },
  {
    id: "eval-043",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-045",
    judgeId: "judge-nora",
    projectId: "project-009",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-043-score-1",
        evaluationId: "eval-043",
        criterionId: "criterion-innovation",
        score: 8.3,
      },
      {
        id: "eval-043-score-2",
        evaluationId: "eval-043",
        criterionId: "criterion-impact",
        score: 6.8,
      },
      {
        id: "eval-043-score-3",
        evaluationId: "eval-043",
        criterionId: "criterion-feasibility",
        score: 7.9,
        comment: "من أفضل المشاريع من ناحية جاهزية النموذج الأولي.",
      },
      {
        id: "eval-043-score-4",
        evaluationId: "eval-043",
        criterionId: "criterion-presentation",
        score: 7.5,
      },
    ],
    submittedAt: "2026-08-21T17:30:00.000Z",
    createdAt: "2026-08-21T17:30:00.000Z",
    updatedAt: "2026-08-21T17:30:00.000Z",
  },
  {
    id: "eval-044",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-046",
    judgeId: "judge-ahmad",
    projectId: "project-010",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-044-score-1",
        evaluationId: "eval-044",
        criterionId: "criterion-innovation",
        score: 8.8,
      },
      {
        id: "eval-044-score-2",
        evaluationId: "eval-044",
        criterionId: "criterion-impact",
        score: 9.7,
        comment: "من أفضل المشاريع من ناحية جاهزية النموذج الأولي.",
      },
      {
        id: "eval-044-score-3",
        evaluationId: "eval-044",
        criterionId: "criterion-feasibility",
        score: 9.2,
      },
      {
        id: "eval-044-score-4",
        evaluationId: "eval-044",
        criterionId: "criterion-presentation",
        score: 7.8,
      },
    ],
    submittedAt: "2026-08-21T18:15:00.000Z",
    createdAt: "2026-08-21T18:15:00.000Z",
    updatedAt: "2026-08-21T18:15:00.000Z",
  },
  {
    id: "eval-045",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-047",
    judgeId: "judge-mohammed",
    projectId: "project-010",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-045-score-1",
        evaluationId: "eval-045",
        criterionId: "criterion-innovation",
        score: 6.6,
        comment: "من أفضل المشاريع من ناحية جاهزية النموذج الأولي.",
      },
      {
        id: "eval-045-score-2",
        evaluationId: "eval-045",
        criterionId: "criterion-impact",
        score: 9.5,
      },
      {
        id: "eval-045-score-3",
        evaluationId: "eval-045",
        criterionId: "criterion-feasibility",
        score: 8.1,
      },
      {
        id: "eval-045-score-4",
        evaluationId: "eval-045",
        criterionId: "criterion-presentation",
        score: 9.4,
      },
    ],
    submittedAt: "2026-08-21T19:00:00.000Z",
    createdAt: "2026-08-21T19:00:00.000Z",
    updatedAt: "2026-08-21T19:00:00.000Z",
  },
  {
    id: "eval-046",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-048",
    judgeId: "judge-khalid",
    projectId: "project-010",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-046-score-1",
        evaluationId: "eval-046",
        criterionId: "criterion-innovation",
        score: 9.6,
      },
      {
        id: "eval-046-score-2",
        evaluationId: "eval-046",
        criterionId: "criterion-impact",
        score: 7.8,
      },
      {
        id: "eval-046-score-3",
        evaluationId: "eval-046",
        criterionId: "criterion-feasibility",
        score: 6.6,
      },
      {
        id: "eval-046-score-4",
        evaluationId: "eval-046",
        criterionId: "criterion-presentation",
        score: 8.5,
        comment: "يحتاج الفريق لتوضيح خطة التوسّع بعد الإطلاق.",
      },
    ],
    submittedAt: "2026-08-21T19:45:00.000Z",
    createdAt: "2026-08-21T19:45:00.000Z",
    updatedAt: "2026-08-21T19:45:00.000Z",
  },
  {
    id: "eval-047",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-049",
    judgeId: "judge-sarah",
    projectId: "project-010",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-047-score-1",
        evaluationId: "eval-047",
        criterionId: "criterion-innovation",
        score: 9.2,
      },
      {
        id: "eval-047-score-2",
        evaluationId: "eval-047",
        criterionId: "criterion-impact",
        score: 6.8,
      },
      {
        id: "eval-047-score-3",
        evaluationId: "eval-047",
        criterionId: "criterion-feasibility",
        score: 7.6,
        comment: "يحتاج الفريق لتوضيح خطة التوسّع بعد الإطلاق.",
      },
      {
        id: "eval-047-score-4",
        evaluationId: "eval-047",
        criterionId: "criterion-presentation",
        score: 8.2,
      },
    ],
    submittedAt: "2026-08-21T20:30:00.000Z",
    createdAt: "2026-08-21T20:30:00.000Z",
    updatedAt: "2026-08-21T20:30:00.000Z",
  },
  {
    id: "eval-048",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-051",
    judgeId: "judge-ahmad",
    projectId: "project-011",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-048-score-1",
        evaluationId: "eval-048",
        criterionId: "criterion-innovation",
        score: 9.9,
      },
      {
        id: "eval-048-score-2",
        evaluationId: "eval-048",
        criterionId: "criterion-impact",
        score: 8,
        comment: "يحتاج الفريق لتوضيح خطة التوسّع بعد الإطلاق.",
      },
      {
        id: "eval-048-score-3",
        evaluationId: "eval-048",
        criterionId: "criterion-feasibility",
        score: 9.4,
      },
      {
        id: "eval-048-score-4",
        evaluationId: "eval-048",
        criterionId: "criterion-presentation",
        score: 9.4,
      },
    ],
    submittedAt: "2026-08-21T21:15:00.000Z",
    createdAt: "2026-08-21T21:15:00.000Z",
    updatedAt: "2026-08-21T21:15:00.000Z",
  },
  {
    id: "eval-049",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-052",
    judgeId: "judge-mohammed",
    projectId: "project-011",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-049-score-1",
        evaluationId: "eval-049",
        criterionId: "criterion-innovation",
        score: 9,
        comment: "يحتاج الفريق لتوضيح خطة التوسّع بعد الإطلاق.",
      },
      {
        id: "eval-049-score-2",
        evaluationId: "eval-049",
        criterionId: "criterion-impact",
        score: 6.2,
      },
      {
        id: "eval-049-score-3",
        evaluationId: "eval-049",
        criterionId: "criterion-feasibility",
        score: 6.3,
      },
      {
        id: "eval-049-score-4",
        evaluationId: "eval-049",
        criterionId: "criterion-presentation",
        score: 6.7,
      },
    ],
    submittedAt: "2026-08-21T22:00:00.000Z",
    createdAt: "2026-08-21T22:00:00.000Z",
    updatedAt: "2026-08-21T22:00:00.000Z",
  },
  {
    id: "eval-050",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-053",
    judgeId: "judge-khalid",
    projectId: "project-011",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-050-score-1",
        evaluationId: "eval-050",
        criterionId: "criterion-innovation",
        score: 8,
      },
      {
        id: "eval-050-score-2",
        evaluationId: "eval-050",
        criterionId: "criterion-impact",
        score: 8.7,
      },
      {
        id: "eval-050-score-3",
        evaluationId: "eval-050",
        criterionId: "criterion-feasibility",
        score: 9,
      },
      {
        id: "eval-050-score-4",
        evaluationId: "eval-050",
        criterionId: "criterion-presentation",
        score: 10,
        comment: "عرض تقديمي مقنع ومؤشرات أداء واقعية.",
      },
    ],
    submittedAt: "2026-08-21T22:45:00.000Z",
    createdAt: "2026-08-21T22:45:00.000Z",
    updatedAt: "2026-08-21T22:45:00.000Z",
  },
  {
    id: "eval-051",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-055",
    judgeId: "judge-nora",
    projectId: "project-011",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-051-score-1",
        evaluationId: "eval-051",
        criterionId: "criterion-innovation",
        score: 9.3,
      },
      {
        id: "eval-051-score-2",
        evaluationId: "eval-051",
        criterionId: "criterion-impact",
        score: 8.5,
      },
      {
        id: "eval-051-score-3",
        evaluationId: "eval-051",
        criterionId: "criterion-feasibility",
        score: 9.3,
        comment: "عرض تقديمي مقنع ومؤشرات أداء واقعية.",
      },
      {
        id: "eval-051-score-4",
        evaluationId: "eval-051",
        criterionId: "criterion-presentation",
        score: 9.4,
      },
    ],
    submittedAt: "2026-08-21T23:30:00.000Z",
    createdAt: "2026-08-21T23:30:00.000Z",
    updatedAt: "2026-08-21T23:30:00.000Z",
  },
  {
    id: "eval-052",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-056",
    judgeId: "judge-ahmad",
    projectId: "project-012",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-052-score-1",
        evaluationId: "eval-052",
        criterionId: "criterion-innovation",
        score: 8.4,
      },
      {
        id: "eval-052-score-2",
        evaluationId: "eval-052",
        criterionId: "criterion-impact",
        score: 7.4,
        comment: "عرض تقديمي مقنع ومؤشرات أداء واقعية.",
      },
      {
        id: "eval-052-score-3",
        evaluationId: "eval-052",
        criterionId: "criterion-feasibility",
        score: 7.8,
      },
      {
        id: "eval-052-score-4",
        evaluationId: "eval-052",
        criterionId: "criterion-presentation",
        score: 9.5,
      },
    ],
    submittedAt: "2026-08-22T00:15:00.000Z",
    createdAt: "2026-08-22T00:15:00.000Z",
    updatedAt: "2026-08-22T00:15:00.000Z",
  },
  {
    id: "eval-053",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-058",
    judgeId: "judge-khalid",
    projectId: "project-012",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-053-score-1",
        evaluationId: "eval-053",
        criterionId: "criterion-innovation",
        score: 8.7,
        comment: "عرض تقديمي مقنع ومؤشرات أداء واقعية.",
      },
      {
        id: "eval-053-score-2",
        evaluationId: "eval-053",
        criterionId: "criterion-impact",
        score: 7.4,
      },
      {
        id: "eval-053-score-3",
        evaluationId: "eval-053",
        criterionId: "criterion-feasibility",
        score: 9.8,
      },
      {
        id: "eval-053-score-4",
        evaluationId: "eval-053",
        criterionId: "criterion-presentation",
        score: 8.5,
      },
    ],
    submittedAt: "2026-08-22T01:00:00.000Z",
    createdAt: "2026-08-22T01:00:00.000Z",
    updatedAt: "2026-08-22T01:00:00.000Z",
  },
  {
    id: "eval-054",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-059",
    judgeId: "judge-sarah",
    projectId: "project-012",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-054-score-1",
        evaluationId: "eval-054",
        criterionId: "criterion-innovation",
        score: 7.3,
      },
      {
        id: "eval-054-score-2",
        evaluationId: "eval-054",
        criterionId: "criterion-impact",
        score: 9.4,
      },
      {
        id: "eval-054-score-3",
        evaluationId: "eval-054",
        criterionId: "criterion-feasibility",
        score: 6.6,
      },
      {
        id: "eval-054-score-4",
        evaluationId: "eval-054",
        criterionId: "criterion-presentation",
        score: 7.5,
        comment: "تنفيذ تقني متقن لكن الأثر المجتمعي يحتاج توضيحًا أكبر.",
      },
    ],
    submittedAt: "2026-08-22T01:45:00.000Z",
    createdAt: "2026-08-22T01:45:00.000Z",
    updatedAt: "2026-08-22T01:45:00.000Z",
  },
  {
    id: "eval-055",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-061",
    judgeId: "judge-ahmad",
    projectId: "project-013",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-055-score-1",
        evaluationId: "eval-055",
        criterionId: "criterion-innovation",
        score: 6.1,
      },
      {
        id: "eval-055-score-2",
        evaluationId: "eval-055",
        criterionId: "criterion-impact",
        score: 6.3,
      },
      {
        id: "eval-055-score-3",
        evaluationId: "eval-055",
        criterionId: "criterion-feasibility",
        score: 8.6,
        comment: "تنفيذ تقني متقن لكن الأثر المجتمعي يحتاج توضيحًا أكبر.",
      },
      {
        id: "eval-055-score-4",
        evaluationId: "eval-055",
        criterionId: "criterion-presentation",
        score: 8.9,
      },
    ],
    submittedAt: "2026-08-22T02:30:00.000Z",
    createdAt: "2026-08-22T02:30:00.000Z",
    updatedAt: "2026-08-22T02:30:00.000Z",
  },
  {
    id: "eval-056",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-062",
    judgeId: "judge-mohammed",
    projectId: "project-013",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-056-score-1",
        evaluationId: "eval-056",
        criterionId: "criterion-innovation",
        score: 9.8,
      },
      {
        id: "eval-056-score-2",
        evaluationId: "eval-056",
        criterionId: "criterion-impact",
        score: 9.5,
        comment: "تنفيذ تقني متقن لكن الأثر المجتمعي يحتاج توضيحًا أكبر.",
      },
      {
        id: "eval-056-score-3",
        evaluationId: "eval-056",
        criterionId: "criterion-feasibility",
        score: 7.9,
      },
      {
        id: "eval-056-score-4",
        evaluationId: "eval-056",
        criterionId: "criterion-presentation",
        score: 8.8,
      },
    ],
    submittedAt: "2026-08-22T03:15:00.000Z",
    createdAt: "2026-08-22T03:15:00.000Z",
    updatedAt: "2026-08-22T03:15:00.000Z",
  },
  {
    id: "eval-057",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-063",
    judgeId: "judge-khalid",
    projectId: "project-013",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-057-score-1",
        evaluationId: "eval-057",
        criterionId: "criterion-innovation",
        score: 6.6,
        comment: "تنفيذ تقني متقن لكن الأثر المجتمعي يحتاج توضيحًا أكبر.",
      },
      {
        id: "eval-057-score-2",
        evaluationId: "eval-057",
        criterionId: "criterion-impact",
        score: 7.1,
      },
      {
        id: "eval-057-score-3",
        evaluationId: "eval-057",
        criterionId: "criterion-feasibility",
        score: 6.6,
      },
      {
        id: "eval-057-score-4",
        evaluationId: "eval-057",
        criterionId: "criterion-presentation",
        score: 6.2,
      },
    ],
    submittedAt: "2026-08-22T04:00:00.000Z",
    createdAt: "2026-08-22T04:00:00.000Z",
    updatedAt: "2026-08-22T04:00:00.000Z",
  },
  {
    id: "eval-058",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-064",
    judgeId: "judge-sarah",
    projectId: "project-013",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-058-score-1",
        evaluationId: "eval-058",
        criterionId: "criterion-innovation",
        score: 7.2,
      },
      {
        id: "eval-058-score-2",
        evaluationId: "eval-058",
        criterionId: "criterion-impact",
        score: 7.8,
      },
      {
        id: "eval-058-score-3",
        evaluationId: "eval-058",
        criterionId: "criterion-feasibility",
        score: 8.3,
      },
      {
        id: "eval-058-score-4",
        evaluationId: "eval-058",
        criterionId: "criterion-presentation",
        score: 8.9,
        comment: "فكرة قوية وعرض واضح، يُنصح بتوسيع دراسة السوق.",
      },
    ],
    submittedAt: "2026-08-22T04:45:00.000Z",
    createdAt: "2026-08-22T04:45:00.000Z",
    updatedAt: "2026-08-22T04:45:00.000Z",
  },
  {
    id: "eval-059",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-065",
    judgeId: "judge-nora",
    projectId: "project-013",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-059-score-1",
        evaluationId: "eval-059",
        criterionId: "criterion-innovation",
        score: 9.2,
      },
      {
        id: "eval-059-score-2",
        evaluationId: "eval-059",
        criterionId: "criterion-impact",
        score: 9.1,
      },
      {
        id: "eval-059-score-3",
        evaluationId: "eval-059",
        criterionId: "criterion-feasibility",
        score: 6.8,
        comment: "فكرة قوية وعرض واضح، يُنصح بتوسيع دراسة السوق.",
      },
      {
        id: "eval-059-score-4",
        evaluationId: "eval-059",
        criterionId: "criterion-presentation",
        score: 8.7,
      },
    ],
    submittedAt: "2026-08-22T05:30:00.000Z",
    createdAt: "2026-08-22T05:30:00.000Z",
    updatedAt: "2026-08-22T05:30:00.000Z",
  },
  {
    id: "eval-060",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-066",
    judgeId: "judge-ahmad",
    projectId: "project-014",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-060-score-1",
        evaluationId: "eval-060",
        criterionId: "criterion-innovation",
        score: 8.1,
      },
      {
        id: "eval-060-score-2",
        evaluationId: "eval-060",
        criterionId: "criterion-impact",
        score: 7.8,
        comment: "فكرة قوية وعرض واضح، يُنصح بتوسيع دراسة السوق.",
      },
      {
        id: "eval-060-score-3",
        evaluationId: "eval-060",
        criterionId: "criterion-feasibility",
        score: 7.9,
      },
      {
        id: "eval-060-score-4",
        evaluationId: "eval-060",
        criterionId: "criterion-presentation",
        score: 7.8,
      },
    ],
    submittedAt: "2026-08-22T06:15:00.000Z",
    createdAt: "2026-08-22T06:15:00.000Z",
    updatedAt: "2026-08-22T06:15:00.000Z",
  },
  {
    id: "eval-061",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-067",
    judgeId: "judge-mohammed",
    projectId: "project-014",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-061-score-1",
        evaluationId: "eval-061",
        criterionId: "criterion-innovation",
        score: 7.7,
        comment: "فكرة قوية وعرض واضح، يُنصح بتوسيع دراسة السوق.",
      },
      {
        id: "eval-061-score-2",
        evaluationId: "eval-061",
        criterionId: "criterion-impact",
        score: 7.3,
      },
      {
        id: "eval-061-score-3",
        evaluationId: "eval-061",
        criterionId: "criterion-feasibility",
        score: 7.2,
      },
      {
        id: "eval-061-score-4",
        evaluationId: "eval-061",
        criterionId: "criterion-presentation",
        score: 6.6,
      },
    ],
    submittedAt: "2026-08-22T07:00:00.000Z",
    createdAt: "2026-08-22T07:00:00.000Z",
    updatedAt: "2026-08-22T07:00:00.000Z",
  },
  {
    id: "eval-062",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-068",
    judgeId: "judge-khalid",
    projectId: "project-014",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-062-score-1",
        evaluationId: "eval-062",
        criterionId: "criterion-innovation",
        score: 8,
      },
      {
        id: "eval-062-score-2",
        evaluationId: "eval-062",
        criterionId: "criterion-impact",
        score: 7.1,
      },
      {
        id: "eval-062-score-3",
        evaluationId: "eval-062",
        criterionId: "criterion-feasibility",
        score: 8.1,
      },
      {
        id: "eval-062-score-4",
        evaluationId: "eval-062",
        criterionId: "criterion-presentation",
        score: 8.2,
        comment: "من أفضل المشاريع من ناحية جاهزية النموذج الأولي.",
      },
    ],
    submittedAt: "2026-08-22T07:45:00.000Z",
    createdAt: "2026-08-22T07:45:00.000Z",
    updatedAt: "2026-08-22T07:45:00.000Z",
  },
  {
    id: "eval-063",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-071",
    judgeId: "judge-ahmad",
    projectId: "project-015",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-063-score-1",
        evaluationId: "eval-063",
        criterionId: "criterion-innovation",
        score: 8.6,
      },
      {
        id: "eval-063-score-2",
        evaluationId: "eval-063",
        criterionId: "criterion-impact",
        score: 7.7,
      },
      {
        id: "eval-063-score-3",
        evaluationId: "eval-063",
        criterionId: "criterion-feasibility",
        score: 6.5,
        comment: "من أفضل المشاريع من ناحية جاهزية النموذج الأولي.",
      },
      {
        id: "eval-063-score-4",
        evaluationId: "eval-063",
        criterionId: "criterion-presentation",
        score: 6,
      },
    ],
    submittedAt: "2026-08-22T08:30:00.000Z",
    createdAt: "2026-08-22T08:30:00.000Z",
    updatedAt: "2026-08-22T08:30:00.000Z",
  },
  {
    id: "eval-064",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-073",
    judgeId: "judge-khalid",
    projectId: "project-015",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-064-score-1",
        evaluationId: "eval-064",
        criterionId: "criterion-innovation",
        score: 6.6,
      },
      {
        id: "eval-064-score-2",
        evaluationId: "eval-064",
        criterionId: "criterion-impact",
        score: 9.8,
        comment: "من أفضل المشاريع من ناحية جاهزية النموذج الأولي.",
      },
      {
        id: "eval-064-score-3",
        evaluationId: "eval-064",
        criterionId: "criterion-feasibility",
        score: 6.3,
      },
      {
        id: "eval-064-score-4",
        evaluationId: "eval-064",
        criterionId: "criterion-presentation",
        score: 9.5,
      },
    ],
    submittedAt: "2026-08-22T09:15:00.000Z",
    createdAt: "2026-08-22T09:15:00.000Z",
    updatedAt: "2026-08-22T09:15:00.000Z",
  },
  {
    id: "eval-065",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-074",
    judgeId: "judge-sarah",
    projectId: "project-015",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-065-score-1",
        evaluationId: "eval-065",
        criterionId: "criterion-innovation",
        score: 7.7,
        comment: "من أفضل المشاريع من ناحية جاهزية النموذج الأولي.",
      },
      {
        id: "eval-065-score-2",
        evaluationId: "eval-065",
        criterionId: "criterion-impact",
        score: 8,
      },
      {
        id: "eval-065-score-3",
        evaluationId: "eval-065",
        criterionId: "criterion-feasibility",
        score: 6.4,
      },
      {
        id: "eval-065-score-4",
        evaluationId: "eval-065",
        criterionId: "criterion-presentation",
        score: 9.3,
      },
    ],
    submittedAt: "2026-08-22T10:00:00.000Z",
    createdAt: "2026-08-22T10:00:00.000Z",
    updatedAt: "2026-08-22T10:00:00.000Z",
  },
  {
    id: "eval-066",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-075",
    judgeId: "judge-nora",
    projectId: "project-015",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-066-score-1",
        evaluationId: "eval-066",
        criterionId: "criterion-innovation",
        score: 6.2,
      },
      {
        id: "eval-066-score-2",
        evaluationId: "eval-066",
        criterionId: "criterion-impact",
        score: 7.5,
      },
      {
        id: "eval-066-score-3",
        evaluationId: "eval-066",
        criterionId: "criterion-feasibility",
        score: 6.9,
      },
      {
        id: "eval-066-score-4",
        evaluationId: "eval-066",
        criterionId: "criterion-presentation",
        score: 8.8,
        comment: "يحتاج الفريق لتوضيح خطة التوسّع بعد الإطلاق.",
      },
    ],
    submittedAt: "2026-08-22T10:45:00.000Z",
    createdAt: "2026-08-22T10:45:00.000Z",
    updatedAt: "2026-08-22T10:45:00.000Z",
  },
  {
    id: "eval-067",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-077",
    judgeId: "judge-mohammed",
    projectId: "project-016",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-067-score-1",
        evaluationId: "eval-067",
        criterionId: "criterion-innovation",
        score: 8.3,
      },
      {
        id: "eval-067-score-2",
        evaluationId: "eval-067",
        criterionId: "criterion-impact",
        score: 6.4,
      },
      {
        id: "eval-067-score-3",
        evaluationId: "eval-067",
        criterionId: "criterion-feasibility",
        score: 9.9,
        comment: "يحتاج الفريق لتوضيح خطة التوسّع بعد الإطلاق.",
      },
      {
        id: "eval-067-score-4",
        evaluationId: "eval-067",
        criterionId: "criterion-presentation",
        score: 9,
      },
    ],
    submittedAt: "2026-08-22T11:30:00.000Z",
    createdAt: "2026-08-22T11:30:00.000Z",
    updatedAt: "2026-08-22T11:30:00.000Z",
  },
  {
    id: "eval-068",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-078",
    judgeId: "judge-khalid",
    projectId: "project-016",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-068-score-1",
        evaluationId: "eval-068",
        criterionId: "criterion-innovation",
        score: 8.6,
      },
      {
        id: "eval-068-score-2",
        evaluationId: "eval-068",
        criterionId: "criterion-impact",
        score: 9.2,
        comment: "يحتاج الفريق لتوضيح خطة التوسّع بعد الإطلاق.",
      },
      {
        id: "eval-068-score-3",
        evaluationId: "eval-068",
        criterionId: "criterion-feasibility",
        score: 8.2,
      },
      {
        id: "eval-068-score-4",
        evaluationId: "eval-068",
        criterionId: "criterion-presentation",
        score: 9.2,
      },
    ],
    submittedAt: "2026-08-22T12:15:00.000Z",
    createdAt: "2026-08-22T12:15:00.000Z",
    updatedAt: "2026-08-22T12:15:00.000Z",
  },
  {
    id: "eval-069",
    hackathonId: HACKATHON_ID,
    assignmentId: "assign-079",
    judgeId: "judge-sarah",
    projectId: "project-016",
    status: EvaluationStatus.Submitted,
    scores: [
      {
        id: "eval-069-score-1",
        evaluationId: "eval-069",
        criterionId: "criterion-innovation",
        score: 8.1,
        comment: "يحتاج الفريق لتوضيح خطة التوسّع بعد الإطلاق.",
      },
      {
        id: "eval-069-score-2",
        evaluationId: "eval-069",
        criterionId: "criterion-impact",
        score: 6.7,
      },
      {
        id: "eval-069-score-3",
        evaluationId: "eval-069",
        criterionId: "criterion-feasibility",
        score: 6.3,
      },
      {
        id: "eval-069-score-4",
        evaluationId: "eval-069",
        criterionId: "criterion-presentation",
        score: 6.4,
      },
    ],
    submittedAt: "2026-08-22T13:00:00.000Z",
    createdAt: "2026-08-22T13:00:00.000Z",
    updatedAt: "2026-08-22T13:00:00.000Z",
  },
];
