import type { Project } from "@/lib/domain/project";
import { HACKATHON_ID } from "./hackathons";

export const mockProjects: Project[] = [
  {
    id: "project-001",
    hackathonId: HACKATHON_ID,
    projectNumber: 1,
    teamName: "فريق فينيكس",
    projectName: "منصة تتبّع الأمراض المزمنة",
    description:
      "تطبيق ذكي يساعد مرضى السكري وضغط الدم على متابعة مؤشراتهم الصحية وربطها مباشرة بطبيبهم المعالج.",
    category: "الصحة الرقمية",
    projectUrl: "https://github.com/team-phoenix/chronic-tracker",
    demoUrl: "https://demo.innovationraces.local/phoenix",
    createdAt: "2026-08-18T09:00:00.000Z",
    updatedAt: "2026-08-18T09:00:00.000Z",
  },
  {
    id: "project-002",
    hackathonId: HACKATHON_ID,
    projectNumber: 2,
    teamName: "فريق ألفا",
    projectName: "مساعد المعلم الذكي",
    description:
      "أداة تساعد المعلمين على إعداد الاختبارات وتحليل أداء الطلاب تلقائيًا بالاعتماد على نتائج الواجبات السابقة.",
    category: "التعليم",
    projectUrl: "https://github.com/team-alpha/smart-teacher",
    demoUrl: "https://demo.innovationraces.local/alpha",
    createdAt: "2026-08-18T09:05:00.000Z",
    updatedAt: "2026-08-18T09:05:00.000Z",
  },
  {
    id: "project-003",
    hackathonId: HACKATHON_ID,
    projectNumber: 3,
    teamName: "فريق فيجن",
    projectName: "نظام إدارة النفايات الذكي",
    description:
      "حلول إنترنت الأشياء لمراقبة مستوى امتلاء الحاويات في الأحياء السكنية وتحسين مسارات جمع النفايات.",
    category: "الاستدامة",
    projectUrl: "https://github.com/team-vision/smart-waste",
    demoUrl: "https://demo.innovationraces.local/vision",
    createdAt: "2026-08-18T09:10:00.000Z",
    updatedAt: "2026-08-18T09:10:00.000Z",
  },
  {
    id: "project-004",
    hackathonId: HACKATHON_ID,
    projectNumber: 4,
    teamName: "فريق نبض",
    projectName: "تطبيق الدعم النفسي عن بُعد",
    description:
      "منصة تربط الأفراد بمختصين نفسيين معتمدين عبر جلسات فيديو مشفّرة مع متابعة دورية للحالة.",
    category: "الصحة الرقمية",
    projectUrl: "https://github.com/team-nabd/remote-support",
    demoUrl: "https://demo.innovationraces.local/nabd",
    createdAt: "2026-08-18T09:15:00.000Z",
    updatedAt: "2026-08-18T09:15:00.000Z",
  },
  {
    id: "project-005",
    hackathonId: HACKATHON_ID,
    projectNumber: 5,
    teamName: "فريق مسار",
    projectName: "منصة تدريب المهارات المهنية",
    description:
      "مسارات تعلّم قصيرة موجهة لسوق العمل المحلي مع شهادات إتمام معتمدة من شركاء التوظيف.",
    category: "التعليم",
    projectUrl: "https://github.com/team-masar/career-paths",
    demoUrl: "https://demo.innovationraces.local/masar",
    createdAt: "2026-08-18T09:20:00.000Z",
    updatedAt: "2026-08-18T09:20:00.000Z",
  },
  {
    id: "project-006",
    hackathonId: HACKATHON_ID,
    projectNumber: 6,
    teamName: "فريق ريّان",
    projectName: "نظام ري زراعي ذكي",
    description:
      "أجهزة استشعار رطوبة تربة موصولة بتطبيق جوال يوصي بجدولة الري الأمثل لتقليل استهلاك المياه.",
    category: "الاستدامة",
    projectUrl: "https://github.com/team-rayyan/smart-irrigation",
    demoUrl: "https://demo.innovationraces.local/rayyan",
    createdAt: "2026-08-18T09:25:00.000Z",
    updatedAt: "2026-08-18T09:25:00.000Z",
  },
  {
    id: "project-007",
    hackathonId: HACKATHON_ID,
    projectNumber: 7,
    teamName: "فريق إتقان",
    projectName: "منصة مراجعة العقود القانونية",
    description:
      "أداة تحلل العقود التجارية وتُبرز البنود عالية المخاطر لتسريع مراجعة الفرق القانونية الصغيرة.",
    category: "القطاع القانوني",
    projectUrl: "https://github.com/team-itqan/contract-review",
    demoUrl: "https://demo.innovationraces.local/itqan",
    createdAt: "2026-08-18T09:30:00.000Z",
    updatedAt: "2026-08-18T09:30:00.000Z",
  },
  {
    id: "project-008",
    hackathonId: HACKATHON_ID,
    projectNumber: 8,
    teamName: "فريق واحة",
    projectName: "سوق إلكتروني للمنتجات الحرفية",
    description:
      "منصة تتيح للحرفيين المحليين عرض وبيع منتجاتهم اليدوية مباشرة مع خدمات شحن مبسّطة.",
    category: "التجارة الإلكترونية",
    projectUrl: "https://github.com/team-waha/craft-market",
    demoUrl: "https://demo.innovationraces.local/waha",
    createdAt: "2026-08-18T09:35:00.000Z",
    updatedAt: "2026-08-18T09:35:00.000Z",
  },
  {
    id: "project-009",
    hackathonId: HACKATHON_ID,
    projectNumber: 9,
    teamName: "فريق درب",
    projectName: "تطبيق تخطيط النقل الجماعي",
    description:
      "يجمع بيانات الحافلات والمترو في مدينة واحدة ليقترح للمستخدم أفضل مسار متعدد الوسائط.",
    category: "النقل والمواصلات",
    projectUrl: "https://github.com/team-darb/transit-planner",
    demoUrl: "https://demo.innovationraces.local/darb",
    createdAt: "2026-08-18T09:40:00.000Z",
    updatedAt: "2026-08-18T09:40:00.000Z",
  },
  {
    id: "project-010",
    hackathonId: HACKATHON_ID,
    projectNumber: 10,
    teamName: "فريق أثير",
    projectName: "منصة بودكاست تعليمي للأطفال",
    description:
      "محتوى صوتي تفاعلي موجّه للأطفال من عمر 6-12 سنة يغطي مواد العلوم والرياضيات بأسلوب قصصي.",
    category: "التعليم",
    projectUrl: "https://github.com/team-atheer/kids-podcast",
    demoUrl: "https://demo.innovationraces.local/atheer",
    createdAt: "2026-08-18T09:45:00.000Z",
    updatedAt: "2026-08-18T09:45:00.000Z",
  },
  {
    id: "project-011",
    hackathonId: HACKATHON_ID,
    projectNumber: 11,
    teamName: "فريق سند",
    projectName: "منصة التبرعات العينية المباشرة",
    description:
      "تربط المتبرعين بالجمعيات الخيرية مباشرة لتوصيل الاحتياجات العينية دون وسطاء وبتتبع شفاف.",
    category: "العمل الخيري",
    projectUrl: "https://github.com/team-sanad/direct-donations",
    demoUrl: "https://demo.innovationraces.local/sanad",
    createdAt: "2026-08-18T09:50:00.000Z",
    updatedAt: "2026-08-18T09:50:00.000Z",
  },
  {
    id: "project-012",
    hackathonId: HACKATHON_ID,
    projectNumber: 12,
    teamName: "فريق نماء",
    projectName: "لوحة تحليلات للمشاريع الصغيرة",
    description:
      "لوحة تحكم بسيطة تجمع بيانات المبيعات والمصروفات لأصحاب المشاريع الصغيرة وتقدّم توصيات عملية.",
    category: "الأعمال",
    projectUrl: "https://github.com/team-nama/sme-analytics",
    demoUrl: "https://demo.innovationraces.local/nama",
    createdAt: "2026-08-18T09:55:00.000Z",
    updatedAt: "2026-08-18T09:55:00.000Z",
  },
  {
    id: "project-013",
    hackathonId: HACKATHON_ID,
    projectNumber: 13,
    teamName: "فريق حصاد",
    projectName: "منصة ربط المزارعين بالمشترين",
    description:
      "سوق رقمي يربط صغار المزارعين مباشرة بتجار الجملة لتقليل الفاقد الزراعي وتحسين هامش الربح.",
    category: "الزراعة",
    projectUrl: "https://github.com/team-hasad/farm-market",
    demoUrl: "https://demo.innovationraces.local/hasad",
    createdAt: "2026-08-18T10:00:00.000Z",
    updatedAt: "2026-08-18T10:00:00.000Z",
  },
  {
    id: "project-014",
    hackathonId: HACKATHON_ID,
    projectNumber: 14,
    teamName: "فريق يقين",
    projectName: "أداة كشف المعلومات المضللة",
    description:
      "إضافة متصفح تساعد القارئ على تقييم مصداقية الأخبار المتداولة عبر مطابقتها بمصادر موثوقة.",
    category: "الإعلام",
    projectUrl: "https://github.com/team-yaqeen/fact-check",
    demoUrl: "https://demo.innovationraces.local/yaqeen",
    createdAt: "2026-08-18T10:05:00.000Z",
    updatedAt: "2026-08-18T10:05:00.000Z",
  },
  {
    id: "project-015",
    hackathonId: HACKATHON_ID,
    projectNumber: 15,
    teamName: "فريق تمكين",
    projectName: "منصة توظيف لذوي الإعاقة",
    description:
      "منصة توظيف متخصصة تراعي متطلبات إمكانية الوصول وتربط الباحثين عن عمل من ذوي الإعاقة بشركاء التوظيف.",
    category: "الأعمال",
    projectUrl: "https://github.com/team-tamkeen/inclusive-hiring",
    demoUrl: "https://demo.innovationraces.local/tamkeen",
    createdAt: "2026-08-18T10:10:00.000Z",
    updatedAt: "2026-08-18T10:10:00.000Z",
  },
  {
    id: "project-016",
    hackathonId: HACKATHON_ID,
    projectNumber: 16,
    teamName: "فريق سراج",
    projectName: "نظام إدارة الطاقة المنزلية",
    description:
      "جهاز ذكي يراقب استهلاك الكهرباء لكل غرفة على حدة ويقترح تعديلات لتقليل الفاتورة الشهرية.",
    category: "الاستدامة",
    projectUrl: "https://github.com/team-siraj/home-energy",
    demoUrl: "https://demo.innovationraces.local/siraj",
    createdAt: "2026-08-18T10:15:00.000Z",
    updatedAt: "2026-08-18T10:15:00.000Z",
  },
];
